### PR TITLE
WIP: py3k fixes.

### PR DESCRIPTION
**Pull request by rmcgibbo**
I got down to 11 test failures w/ py3.4.3.

### CODE REVIEW

**Comment by jturney** [comment]
Have you tested this against Python 2, too? I'm getting the following error at execution time on my Mac with Python 2.7:

```
Traceback (most recent call last):
  File "<string>", line 29, in <module>
  File "/Users/jturney/Code/Chemistry/psi4/source/lib/python/driver.py", line 618, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "/Users/jturney/Code/Chemistry/psi4/source/lib/python/proc.py", line 2123, in run_adc
    scf_helper(name, **kwargs)
  File "/Users/jturney/Code/Chemistry/psi4/source/lib/python/proc.py", line 1457, in scf_helper
    e_scf = psi4.scf(precallback, postcallback)
TypeError: No registered converter was able to produce a C++ rvalue of type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > from this Python object of type unicode
```

**Comment by rmcgibbo** [comment]
I saw one like that before. I'll try to track it down. I haven't tested this PR against py2 though. Do you have any idea if any custom from_python typemaps / convereters are registered currently registered?

**Comment by loriab** [comment]
Wow, thank you!

I'm not going to merge this immediately because I want to apply your changes to the actual qcdb repository code (this is an awkward-for-git snapshot of the qcdb repository rather than a proper submodule). And I don't want to perturb qcdb at the moment because of ACS next week. Or Jet can merge it into psi4, and I'll copy to repo week after next.

**Comment by jturney** [comment]
@loriab Please don't merge it until it works with Python 2!

**Comment by rmcgibbo** [comment]
Yeah, I think it's probably not ready to merge anyways :)

**Comment by jturney** [comment]
@rmcgibbo There should be convertors in the code somewhere. Can't remember off the top of my head where.

**Comment by loriab** [comment]
@jturney I'm deferring this until week of Aug 24 or 31 for psi4/qcdb simultaneously. If you wanted to do merge into psi4 alone, go ahead. Agree that mustn't break py2.

**Comment by rmcgibbo** [comment]
@jturney: i think i've fixed the py2 issue, if you want to give it a spin again.

**Comment by jturney** [comment]
@rmcgibbo Looks like that fixed it. Once the tests finish on my box I'll merge in the changes.

**Comment by rmcgibbo** [comment]
There might still be more failures. I was seeing an infinite loop somewhere with a `__getattribute__` recursively calling itself in `libmintsmolecule.py` I think.

**Comment by jturney** [comment]
Okay, I'll report back any failures I have.

**Comment by loriab** [comment]
I'd bet that's the dratted feature that let's you set a molecule w/o fully specifying it. Enables ``molecule mol {He 0 0 0\nHe 0 0 x}\n mol.x = 2.0``. It's set up to closely mimic same in libmints. Makes qcdb.Molecule un-pickleable. Basically, known issue, no clear remedy.

**Comment by jturney** [comment]
All tests (except the normal failing ones) has passed on my box with Python2. I'm going to accept the pull request.

**Pull request merged**
