### PR TITLE
Added missing return, which was causing a segfault with Linux Clang.

### PR DESCRIPTION
**Pull request by andysim**

### CODE REVIEW

**Comment by andysim** [comment]
This commit *should* fix the Travis CI builds.

**Comment by loriab** [comment]
Yay, two clang successes! That return statement looks like a bother to track down.

**Comment by dgasmith** [comment]
Fixed travis CI _and_ did a PR from your own fork? Were going to be a real GitHub using organization before we know it.

**Comment by andysim** [comment]
@loriab it was an absolute nightmare, because it results in an illegal instruction that crashes Valgrind and gdb.  @dgasmith I'm hoping this workflow catches on, because we can catch nasty bugs before they enter the main repo.  We probably went a year without seeing any really difficult bugs and now we've had two of them in the last couple of weeks, which both came after Travis was set up, thankfully.

**Comment by loriab** [comment]
Yikes, you have my sympathy and gratitude. Fortunate that you and Jet got CI working before that particular sync with private that brought over the coupled-cluster changes.

Yes, the PR workflow should help more people read changes. And CI, apart from its own benefits, justifies the PR workflow. And the repo renaming and recentering on public should get everyone developing off the same master, which will be a relief.

**Comment by andysim** [comment]
The wavefunction passing and repo rejigging are far more difficult than the 6 character fix that I just pushed, so kudos to both of you.  I think Psi4 will be in very good shape about a month from now.  Perhaps we should add a CONTRIBUTING.md file that recommends the PR approach to adding code, both for core developers and noobs alike?

**Comment by jturney** [comment]
Nice catch!

**Pull request merged**
