### PR TITLE
Retry optking improvements for TS and linear angles

### PR DESCRIPTION
**Pull request by psi-rking**

### CODE REVIEW

**Comment by andysim** [comment]
Have you tried running it through Valgrind?  If it's an uninitialized variable that GCC is magically zeroing out for you, Valgrind will tell you about it.

**Comment by psi-rking** [comment]
I tried valgrind.  I found a couple of functions with assumed return type
due to an incorrect syntax (probably the problem), one invalid read (going
8 bytes too far), and a couple of uninitialized variables that probably
don't matter.  Enough to give it another go.

--
Dr. Rollin A. King
Professor and Chair of Chemistry
Bethel University
rking@bethel.edu

**Comment by dgasmith** [comment]
As a note this is a perfect example where you probably want to squash commits so that the git history is more understandable. A quick rundown would be something like the following:

`git rebase -i HEAD~5`
Change the commits that you no longer want from `pick` to `squash`, save the file.

See [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages) for more information.

**Comment by psi-rking** [comment]
Thanks for the tip.  Would you elaborate on "Don't include any commit
already pushed to a central server" a quote from the link you sent?  Would
I need to cancel the pull request, then go ahead and push the squashed
version to my fork, then reinitiate the pull request?

--
Dr. Rollin A. King
Professor and Chair of Chemistry
Bethel University
rking@bethel.edu

**Comment by dgasmith** [comment]
There is no need to cancel the pull request, modifying the pull request is perfectly fine. I think that language is specific to git and not github. For github I would change it to "Do not change any commit already pushed to the master branch".

Out of curiosity would a link like [this](http://docs.scipy.org/doc/numpy-1.10.1/dev/gitwash/development_workflow.html#rewriting-commit-history) be a better way to demonstrate squashing?

**Comment by psi-rking** [comment]
Thanks, yes, that link is a little clearer.

**Comment by andysim** [comment]
Looks like it's working now. Great work, Rollin.

**Comment by CDSherrill** [comment]
Really liking this new github/TravisCI workflow of pull request / automatic testing / fix any remaining problems and let people comment on pull request.  TravisCI is already showing its value by finding us some of these bugs.

**Pull request merged**
