### PR TITLE
optking improvements for TS and linear angles

### PR DESCRIPTION
**Pull request by psi-rking**

### CODE REVIEW

**Comment by andysim** [comment]
Just a heads-up: you don't need to close the PR and reopen it to apply fixes.  The request is automatically updated as you add features / fixes, until it gets merged.

**Comment by psi-rking** [comment]
Thanks for the tip.  But does it matter if it claims to already be in the
testing stage?  I presumed that the test calculations might already be
running and that's why I closed it.

**Comment by andysim** [comment]
No, it doesn't matter.  The testing is triggered every time a commit is pushed, or every time a PR is created.  The bugfix commit (0188418) test is running now, and then the merge commit that followed it will be tested after that (both appear on this PR).  Then the tests for the new PR will pick up, but will be identical to the tests for 9a20655 from here.  Closing a PR doesn't stop Travis from running the tests.

**Comment by psi-rking** [comment]
Thanks for the description.  Very helpful.  To verify, if I make a PR with
5 commits, and only the first 3 commits pass the tests, then those first
three are pulled and included.  That is, final incorporation is approved
one commit at a time.

**Comment by andysim** [comment]
Not quite.  The testing is just a guide that helps us to determine whether to accept a PR or not; the outcome of the tests does not affect GitHub's handling of the merge at all.  So in your example above, all 5 commits would be pulled in.  I was trying to make the following point, but didn't explain well at all:

Say you open a pull request with three commits, but discover that the tests don't pass.  If you were to continue pushing commits to your GitHub repo branch (the same one you based the PR on), those commits would continue to be added real-time to the original PR automatically.  Therefore there's no need to close the PR when you find that it's broken, and re-open a new one when it's fixed.  In fact I think it's better to just leave the original one open, because it allows a discussion to take place, amongst the commits, and the team can hopefully jump in with solutions to whatever problems were created.  It's up to you, or whomever actually accepts the PR, to make sure that the final commit in the PR passes the tests before accepting it.  The Travis CI testing helps us to quickly make that determination, and GitHub helpfully tells us whether the merge can happen without conflicts.  I hope this clears things up a little.

**Pull request closed without merging**
