### PR TITLE
Document use of PCM

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Comment by loriab** [comment]
Great, we were talking yesterday about how an interfaces doc page was needed, and here it is!

I was going to just mention topic here, but it turned into a write-up, so made an independent issue (https://github.com/psi4/psi4/issues/122). Would you take a look and see if you agree with its strategy?

On the ``pcm {...}`` block, is that the same syntax across the other QC programs that pcmsolver is integrated with?

**Comment by robertodr** [comment]
@loriab  **TL;DR** Yes, the syntax is the same and is described [here](http://pcmsolver.readthedocs.org/en/latest/)

**Lengthy version**
The input to PCMSolver can work like this:

1. Either you use the "native" format that is processed by the module's own Python script. This requires the user to provide an additional input file when submitting the calculation.
2. Either you pass a `struct` with relevant input parameters when initializing the library from within the host. This allows using the host program native syntax. Of course, the host has to define the appropriate input sections.

Since the module has to be interoperable with C/C++ and Fortran hosts, for the moment being (and the foreseeable future), the second strategy is limited to a subset of all possible options to the library.
With @andysim and @lothian we decided for a middle ground in Psi4: The additional input file is incorporated into a section in the Psi4 input that is extracted in the current directory so that PCMSolver's Python script can parse it. This would be strategy 1.5

All programs with an interface to PCMSolver can use Strategy 1 (DALTON, LSDALTON, DIRAC and a couple of others) Only DIRAC can use Strategy 2. Only Psi4 uses strategy 1.5: it was rather easy to implement, since everything runs through Python.

**Comment by loriab** [comment]
Lengthy version very interesting. It slightly pains me that options specification isn't consistent through all of psi4, but having options specification not consistent for pcmsolver across all host programs would be more painful to the dedicated pcmsolver user. Is the ``pcm {...}`` to `pcmsolver.inp` safe for multiple invocations in one psi4 input (I remember labeling temp dirs with random numbers for dftd3)?

I like the multiple input strategies scheme. Would someday you approve of an additional strategy 1.75 where pcm options are specified in psi4 format (e.g., `set pcm_cavity_probe_radius 2`, then the whole pcm collection be written to ``pcmsolver.inp``? That way, could be friendly to the dedicated pcmsolver user and the dedicated psi4 user?

**Comment by robertodr** [comment]
Alas, we didn't think that far ahead when Strategy 1.5 was put into place. But you can see from the tests in `pcm_scf`, `pcm_dft` and `pcm_dipole` that the same PCM input is used across multiple calculations without problem. I can't say (because I haven't checked) if it's because the same parsed file is used throughout (not what we want) or because the intermediate `pcmsolver.inp` is re-parsed for every calculation (what we want)

Strategy 1.75 would be great and would definitely make @lothian happier :smile:

**Pull request merged**
